{
 "title": "5G Simulator Dashboard",
 "tags": [
  "5g",
  "simulator"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") \nFROM \"http_req_duration\" \nWHERE $timeFilter \nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") as total_request_count\nFROM \"http_reqs\" \nWHERE $timeFilter \nGROUP BY time(1s)"
    }
   ]
  },
  {
   "title": "Scenarios executions",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_scenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "scenario_executions",
     "query": "SELECT sum(\"value\") FROM \"scenario_executions\" \nWHERE $timeFilter \nGROUP BY time(1s), \"scenario\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "SELECT count(\"value\") \nFROM \"http_reqs\" \nWHERE $timeFilter \nGROUP BY \"status\""
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")\nFROM \"notification_latency\"\nWHERE $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Throughput Size ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") as input_throughput\nFROM \"inputThroughput_bytes\" \nWHERE $timeFilter \nGROUP BY time(1s)"
    },
    {
     "query": "SELECT sum(\"value\") as output_throughput\nFROM \"outputThroughput_bytes\"\nWHERE $timeFilter \nGROUP BY time(1s)"
    }
   ]
  }
 ]
}